data:extend(
{
    {
        type = "fluid",
        name = "steam-feedwater",
        default_temperature = 15,
        max_temperature = 100,
        heat_capacity = "1KJ",
        base_color = { r = 0, g = 0.34, b = 0.6 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7 },
        icon = "__base__/graphics/icons/fluid/water.png",
        order = "a[fluid]-a[steam-feedwater]",
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59
    },
    {
        type = "fluid",
        name = "steam-saturated",
        default_temperature = 15,
        max_temperature = 120,
        heat_capacity = "1.5KJ",
        base_color = { r = 0, g = 0.34, b = 0.6 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7 },
        icon = "__base__/graphics/icons/fluid/water.png",
        order = "a[fluid]-a[steam-saturated]",
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59
    },
    {
        type = "fluid",
        name = "steam-condensing",
        default_temperature = 120,
        max_temperature = 120,
        heat_capacity = "1KJ",
        base_color = { r = 0, g = 0.34, b = 0.6 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7 },
        icon = "__base__/graphics/icons/fluid/water.png",
        order = "a[fluid]-a[steam-condensing]",
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59
    },
    {
        type = "fluid",
        name = "steam-dry",
        default_temperature = 120,
        max_temperature = 540,
        heat_capacity = "4.5KJ",
        base_color = { r = 0, g = 0.34, b = 0.6 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7 },
        icon = "__base__/graphics/icons/fluid/water.png",
        order = "a[fluid]-a[steam-dry]",
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59
    },
    {
        type = "fluid",
        name = "steam-lp",
        default_temperature = 120,
        max_temperature = 540,
        heat_capacity = "4.5KJ",
        base_color = { r = 0, g = 0.34, b = 0.6 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7 },
        icon = "__base__/graphics/icons/fluid/water.png",
        order = "a[fluid]-a[steam-lp]",
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59
    },
    {
        type = "fluid",
        name = "steam-mp",
        default_temperature = 120,
        max_temperature = 540,
        heat_capacity = "4.5KJ",
        base_color = { r = 0, g = 0.34, b = 0.6 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7 },
        icon = "__base__/graphics/icons/fluid/water.png",
        order = "a[fluid]-a[steam-mp]",
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59
    },
    {
        type = "fluid",
        name = "steam-hp",
        default_temperature = 120,
        max_temperature = 540,
        heat_capacity = "4.5KJ",
        base_color = { r = 0, g = 0.34, b = 0.6 },
        flow_color = { r = 0.7, g = 0.7, b = 0.7 },
        icon = "__base__/graphics/icons/fluid/water.png",
        order = "a[fluid]-a[steam-hp]",
        pressure_to_speed_ratio = 0.4,
        flow_to_energy_ratio = 0.59
    },
} )